### ISSUE TITLE
[BUG] Android, keyboard make cupertino infinity sky)

### ISSUE THREAD

**Issue by bazuka5801** [tech-systems/panes#188]
**Describe the bug**
When I open the keyboard, my Cupertino goes up.
And this problem (no `background` at the bottom) appears on iOS when we turn on the `bounce` animation to `breaks`.
I've tried adding `:after` to `.cupertino-pane` to solve this problem, but i think, it's bicycle stick :)

**To Reproduce**
1. Add input to cupertino
2. Click on input

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/11452353/181632834-2497e5d1-d316-488f-864a-64c4fd6f6be3.png)

**Desktop (please complete the following information):**
 - OS: Android
 - Capacitor App
 - Version API 29

**Comment by roman-rr** [comment]
@bazuka5801 thank you, seems to related to #187 also. Will check.

**Comment by bazuka5801** [comment]
@roman-rr As of today, I have dropped support for android in my project, and now it is too difficult to check this issue for android. I am sure we can close this issue, if something goes wrong in the future, I will let you know.

**Comment by danilabais** [comment]
Hi, 

the bug remained, on Android and iOS (Capasitor). infinity sky only appears when the input is too low to the bottom of the pane. if it is 10 pixels higher, then infinity sky is smaller, if it is even higher, then there is no infinity sky at all. Apparently the indent is somehow incorrectly calculated if the input is low. if you need to write code with this problem - let me know

**Comment by danilabais** [comment]
Behavior similar to ios and android: the lower the input is located to the bottom of the screen, the larger the infinity sky will be

android video: [click](https://www.veed.io/view/c753b895-d702-4d51-b282-36fc0ebb8511?sharingWidget=true&panel=share)
ios video: [click](https://www.veed.io/view/3f008372-b965-4fd7-afcf-afbe68b8c222?panel=share)

settings of capasitor keyboard plugin: 
```
"plugins": {
    "Keyboard": {
      "resize": "body",
      "style": "DARK",
      "resizeOnFullScreen": true
    }
  }
  
```
pane: 
` handleKeyboard: true, // TODO: bug`

**Comment by danilabais** [comment]
Everywhere this bug was closed with crutches.

Here is a quick code for anyone who needs it. Looks to work as it should

```
const fixAndroid = async () => {

    if ((await Device.getInfo()).platform !== 'android') return

    document.addEventListener('click', ({ target }) => {
        const contentEditable = ['TEXTAREA', 'INPUT']
        const offset = 100
        if (!contentEditable.includes(target.tagName)) return
        if (window.innerHeight - target.getBoundingClientRect().bottom < offset) {
            target.scrollIntoView()
        }
    })
}
fixAndroid()
```

**Comment by roman-rr** [comment]
> Everywhere this bug was closed with crutches.
> 
> Here is a quick code for anyone who needs it. Looks to work as it should.
> 
> ps: this code will work if the input is at the bottom only because of the scroll. if it is at the bottom and the scroll is also at the bottom, then layout will help here. You need to make sure that the cupertino-pane content is no more than 100vh, and everything that should scroll is already in this block with overflow-y: auto
> 
> ```
> import { Device } from '@capacitor/device';
> 
> const fixAndroid = async () => {
> 
>     if ((await Device.getInfo()).platform !== 'android') return
> 
>     document.addEventListener('click', ({ target }) => {
>         const contentEditable = ['TEXTAREA', 'INPUT']
>         const offset = 100
>         if (!contentEditable.includes(target.tagName)) return
>         if (window.innerHeight - target.getBoundingClientRect().bottom < offset) {
>             target.scrollIntoView()
>         }
>     })
> }
> fixAndroid()
> ```

Thank you for solution, I will use it for fix.

**Comment by roman-rr** [comment]
Should be fixed
