### ISSUE TITLE
[BUG] Incorrect processing of removing focus from input

### ISSUE THREAD

**Issue by Noothing** [tech-systems/panes#208]
Incorrect processing of removing focus from input on android devices. As the result, styles and meta tag "viewport" is still for focused input, but cupertino is closed. I have tried to make input blur before closing pane, but it is not working

1. Open cupertino with input inside
2. Focus on input
3. Press hand made close button
4. Meta tag 

Some screens:
![image](https://github.com/roman-rr/cupertino-pane/assets/68498236/73444bc6-d3e3-4d76-815e-a8cae8b699f0)
![image](https://github.com/roman-rr/cupertino-pane/assets/68498236/b9161da2-941b-4842-b61d-d3cc64124e23)

Expected behavior:
Removing all styles on blur

 - Device: Samsung Galaxy S22 Ultra
 - OS: Android 13
 - Browser: Chrome
 - Browser version: 114.0.5735.196
 - Cupertino version: 1.3.41

**Comment by Noothing** [comment]
After looking at the source code, I can assume that the change of the "showKeyboard" variable is not working correctly on the mobile device

![image](https://github.com/roman-rr/cupertino-pane/assets/68498236/a8b6fa89-d1f1-44cc-bf8f-7decd5b928a4)

**Comment by roman-rr** [comment]
@Noothing  Thank you. Quick solution for you:
```js
let settings = {
   // ...
   events: {
     onWillDismiss: (ev) => {
         document.documentElement.style.removeProperty('overflow');
         document.body.style.removeProperty('min-height');
         document.querySelector('meta[name=viewport]').setAttribute('content', 'viewport-fit=cover, width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no');
     }
   }
};
```
