### ISSUE TITLE
[BUG] Keyboard reset breakpoints to default

### ISSUE THREAD

**Issue by danilabais** [tech-systems/panes#215]
after keyboard close on android Cupertino-pane reverts to breakpoints set at initialization time, not to breakpoints set with setBreakpoints(…) 

steps: initialize Cupertino-pane with X values ​​in breakpoints.
Set with setBreakpoint() value Y. 
on android open and close the keyboard. 
after closing, pane will revert to X, not Y.

Capasitor, android

**Comment by roman-rr** [comment]
@danilabais Thank you, should be fixed in `v.1.3.6`
