### ISSUE TITLE
[FEAT] Update changelog & Add husky to project

### ISSUE THREAD

**Issue by alexcroox** [tech-systems/panes#219]
**What are you trying to add to Cupertino-Pane?**
It would be useful if there was a way to view a changelog. The current one is outdated and so is the releases. Thanks

**Comment by roman-rr** [comment]
@alexcroox Thank you, I will release `v.1.4.0` in a week and will update `changelog` as well. 
If you wish to contribute, feel free to make pull and add `husky` to project, to hook every commit and update changelog automatically.

**Comment by roman-rr** [comment]
@alexcroox By the way, changelog updated.

**Comment by alexcroox** [comment]
Appreciate it thanks, my dep PR for Cupertino Pane is much more useful :) 

![image](https://github.com/tech-systems/panes/assets/1065835/a58e9efd-ad19-4e80-a049-5bd54cf3deac)
