### ISSUE TITLE
[BUG] Panes cannot be dragged in Chrome

### ISSUE THREAD

**Issue by jamiegyoung** [tech-systems/panes#228]
**Describe the bug**
Dragging and move a Pane does not work Chrome

**To Reproduce**
Create a simple pane using version 1.2.91 or above and attempt to drag it up or down in Chrome
Working version with 1.2.82: https://jsfiddle.net/ngeq9c6z/18/
Broken version with 1.2.91: https://jsfiddle.net/ngeq9c6z/19/

**Expected behavior**
The pane should be moving up and down when clicking and dragging the draggable element up and down

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome 
 - Version: 120.0.6099.109 (Official Build) (64-bit)

**Comment by roman-rr** [comment]
Thank you @jamiegyoung. What do you think about updates into `v.1.4.2` ?

**Comment by jamiegyoung** [comment]
Using 1.4.2 unfortunately doesn't seem to solve this problem from what I can tell. Let me know if I misunderstood the question 👍

**Comment by roman-rr** [comment]
@jamiegyoung I forked your example and upgrade into 1.4.2 here [https://jsfiddle.net/romantonoff/mf4069oj/](https://jsfiddle.net/romantonoff/mf4069oj/)
I don't see any bugs. Can you explain more details?
