### ISSUE TITLE
Vue.js 3 example

### ISSUE THREAD

**Issue by dasturchioka** [tech-systems/panes#236]
Hi. Great work on that project. I was really looking for an example for correct way to initialise the pane in a Vue.js 3 project. 

Thank you for the answer!

**Comment by dasturchioka** [comment]
Hello there again! I share my own code from my project as an example, I hope it helps. 

```typescript
const pane = ref<CupertinoPane>();

onMounted(async () => {
// initialise the pane
  pane.value = new CupertinoPane(".sheet-pane", {
    breaks: {
      top: { enabled: true, height: 460 },
      middle: { enabled: true, height: 240 },
      bottom: { enabled: true, height: 40 },
    },
    initialBreak: "top",
    draggableOver: true,
    parentElement: ".app",
    cssClass: "z-50",
    buttonDestroy: false,
  });

  await pane.value.present({ animate: true });
});
```

In order to understand the options that I implemented in this code, visit the official documentation:
https://panejs.com/settings.html

For `breaks` property especially, I'd really suggest you to take a look at the official documentation to understand what it means:
https://panejs.com/breakpoints.html

**Comment by roman-rr** [comment]
Big thanks @dasturchioka for help.
I will add this to example on docs soon.

**Comment by roman-rr** [comment]
@dasturchioka Here is also Vue 3 wrapper, don't sure its up-to-date, but at least can be explored for examples.
https://github.com/Devrax/v-cupertino

**Comment by dasturchioka** [comment]
Glad to help, @roman-rr. This Vue 3 wrapper didn't work properly the last time I used it. Also the author of this wrapper recommended to use the main library.
![image](https://github.com/tech-systems/panes/assets/111991739/0e331e27-85e1-414a-9ad4-69b6e5584e72)

**Comment by roman-rr** [comment]
Create a good basic example of **Panes** using with **Vue 3** framework.
Including getting control of **Panes** from parent components and using as standalone service. 

https://github.com/tech-systems/panes-vue3-example
