### ISSUE TITLE
fitHeight with breakpoints

### ISSUE THREAD

**Issue by roman-rr** [tech-systems/panes#241]
Hi @roman-rr ,
does the `fitHeight: true` feature work with breakpoints?
I am trying to initialize the CupertinoPane with this configuration:

```ts
new CupertinoPane(HTMLElement, {
  draggableOver: true,
  backdrop: false,
  showDraggable: true,
  bottomClose: true,
  fastSwipeClose: true,
  buttonDestroy: false,
  fastSwipeSensivity: 0,
  fitHeight: true,
  breacks: {
    top: { enabled: true, bounce: false },
    middle: { enabled: true, bounce: false },
    bottom: { enabled: false },
  },
});
```

but I have 2 problems:

- the pane does not change its size based on the content, not even when calling calcFitHeight()
- with `bottom: { enabled: false }`, the `bottomClose` option does not seem to work

Is this a feature not implemented with breakpoints, or am I configuring something wrong?
Thanks!

_Originally posted by @lorenzodianni in https://github.com/tech-systems/panes/issues/113#issuecomment-2198612751_

**Comment by lorenzodianni** [comment]
Thank you @roman-rr , for the quick response!
Do you also know if `bottomClose: true` is supported with breakpoints or not?

Thanks!

**Comment by roman-rr** [comment]
@lorenzodianni Yes, `bottomClose: true` can be used with breakpoints to close pane when its reached `bottom` position.
