### ISSUE TITLE
[QUESTION]  How to test with Jest?

### ISSUE THREAD

**Issue by ArgV04** [tech-systems/panes#246]
**What are you trying to add to Cupertino-Pane?**

Testing a component using CupertinePane with Jest and getting:

`TypeError: cupertino_pane_1.CupertinoPane is not a constructor`

Is there a way to mock the construction?

*Describe your feature request **detailed***

**Is there an alternative at the latest version?**

[ ] Yes (descripe the alternative)
[ ] No

**Is this related to an issue?**

[ ] Yes (Give a link to the issue)
[ ] No

**Comment by roman-rr** [comment]
Hello @ArgV04 thank you for issue!

I created a demo with Jest tests, here is usable repository, please look up into
https://github.com/tech-systems/panejs-jest-test
