### ISSUE TITLE
[BUG] `currentBreak` not accurate `onTransitionEnd` 

### ISSUE THREAD

**Issue by Ghosts** [tech-systems/panes#248]
https://github.com/tech-systems/panes/blob/c5a2ce0e5ecf4943ab86bc97d6a1f54a877ba282/src/events/events.ts#L435C1-L441C71

`onTransitionEnd` is invoked before the transition actually ends, and `currentBreak` is set after the event is invoked, leading to the previous and not current break value being returned

I believe `this.breakpoints.currentBreakpoint = closest;` just needs to be moved to being set as soon as `closest` is known, so the correct value is present on `onDragEnd` and `onTransitionEnd`

**Comment by Ghosts** [comment]
@roman-rr I'd be happy to make a PR for this too if you'd want, as long as the proposed solution above makes sense.

**Comment by roman-rr** [comment]
> @roman-rr I'd be happy to make a PR for this too if you'd want, as long as the proposed solution above makes sense.

Welcome PR 👍🏻 

Please note that there is `currentBreakpoint` under Breakpoints class is probably suppose to be protected/private, and original class `CupertinoPane` method `currentBreak()` planned to use as public method.

Anyway, I will review changes.

**Comment by pinguluk** [comment]
It still doesn't work for me

**Comment by roman-rr** [comment]
Hi @pinguluk 
You not able to receive `currentBreakpoint` or `currentBreak()` with your events?

**Comment by pinguluk** [comment]
> Hi @pinguluk You not able to receive `currentBreakpoint` or `currentBreak()` with your events?

I do receive the state from currentBreak(), but it's the state before the transition.
I have 3 breakpoints (bottom, middle, top) and If, for example, I change from middle to top and put a console.log on onTransitionEnd, it will log "middle" instead of "top".
But if I set a timeout (eg 500ms), it will log "top", which is the correct state.

**Comment by roman-rr** [comment]
@pinguluk Do you using latest version after this pull merged?

**Comment by pinguluk** [comment]
> @pinguluk Do you using latest version after this pull got merged?

Yes
